# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d83hQXvLSlg2HzNaz8ZZzZnAOv-9w1QA
"""

# Commented out IPython magic to ensure Python compatibility.
# Instalar dependencias
# %pip install -q ultralytics pyyaml opencv-python pillow tqdm matplotlib seaborn pandas

# Verificar instalación
import torch
print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"CUDA version: {torch.version.cuda}")
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

# ============================================================
# VARIABLES GLOBALES PARA BACKUP AUTOMÁTICO
# ============================================================

# Variables globales para el sistema de backup
backup_thread_running = False
backup_thread = None

print("✅ Variables globales de backup inicializadas")

"""## 📦 Importar Librerías"""
import os
import sys
import yaml
import torch
import numpy as np
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import cv2
from PIL import Image
import shutil
import json
from tqdm import tqdm

from ultralytics import YOLO
from google.colab import files, drive
from IPython.display import Image as IPImage, display

# Configurar matplotlib
plt.style.use('default')
sns.set_palette("husl")

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"CUDA device: {torch.cuda.get_device_name(0)}")
    print(f"CUDA memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

"""## 📁 Configuración de Datos"""

# ============================================================
# CONFIGURACIÓN DE RUTAS PRINCIPALES (Unificado con HerdNet)
# ============================================================

# Definir la ruta base principal (ajustar según el entorno: Drive o local)
BASE_DIR = Path("/content/drive/MyDrive/aerial-wildlife-count")

# ============================================================
# RUTAS DE IMÁGENES Y ANOTACIONES (COCO JSON) - Igual que HerdNet
# ============================================================

# Rutas de los archivos de anotaciones en formato COCO
TRAIN_ANN_FILE = BASE_DIR / "data" / "coco" / "train" / "train_annotations.json"
VAL_ANN_FILE = BASE_DIR / "data" / "coco" / "val" / "val_annotations.json"
TEST_ANN_FILE = BASE_DIR / "data" / "coco" / "test" / "test_annotations.json"

# Rutas de las carpetas de imágenes correspondientes a cada conjunto
TRAIN_IMG_DIR = BASE_DIR / "data" / "images" / "train"
VAL_IMG_DIR = BASE_DIR / "data" / "images" / "val"
TEST_IMG_DIR = BASE_DIR / "data" / "images" / "test"

# ============================================================
# RUTAS ALTERNATIVAS (Fallback para compatibilidad)
# ============================================================

# Rutas alternativas si no existe la estructura estándar
TRAIN_ANN_FILE_ALT = BASE_DIR / "data" / "groundtruth" / "json" / "big_size" / "train_big_size_A_B_E_K_WH_WB.json"
VAL_ANN_FILE_ALT = BASE_DIR / "data" / "groundtruth" / "json" / "big_size" / "val_big_size_A_B_E_K_WH_WB.json"
TEST_ANN_FILE_ALT = BASE_DIR / "data" / "groundtruth" / "json" / "big_size" / "test_big_size_A_B_E_K_WH_WB.json"

# Rutas alternativas para imágenes
TRAIN_IMG_DIR_ALT = BASE_DIR / "data" / "train"
VAL_IMG_DIR_ALT = BASE_DIR / "data" / "val"
TEST_IMG_DIR_ALT = BASE_DIR / "data" / "test"

# ============================================================
# FUNCIÓN PARA CONFIGURAR DATOS (Unificada con HerdNet)
# ============================================================

def setup_data():
    """Configurar datos desde Google Drive con detección automática de estructura"""

    # Montar Google Drive
    drive.mount('/content/drive')
    print("✅ Google Drive montado")

    # Verificar si existe la estructura estándar (igual que HerdNet)
    if TRAIN_ANN_FILE.exists() and TRAIN_IMG_DIR.exists():
        print("✅ Datos encontrados (estructura estándar COCO)")
        return str(BASE_DIR), "standard"
    elif TRAIN_ANN_FILE_ALT.exists() and TRAIN_IMG_DIR_ALT.exists():
        print("✅ Datos encontrados (estructura alternativa groundtruth)")
        return str(BASE_DIR), "groundtruth"
    else:
        # Buscar en ubicaciones alternativas
        drive_path = "/content/drive/MyDrive"
        possible_paths = [
            f"{drive_path}/aerial-wildlife-count",
            f"{drive_path}/datasets/aerial-wildlife-count",
            f"{drive_path}/Colab Notebooks/aerial-wildlife-count"
        ]

        for path in possible_paths:
            if os.path.exists(path):
                print(f"✅ Dataset encontrado en ubicación alternativa: {path}")
                return path, "legacy"

        print("❌ No se encontró el dataset en Google Drive")
        return None, None

# Configurar datos
data_path, data_type = setup_data()
if data_path:
    print(f"📁 Ruta de datos configurada: {data_path}")
    print(f"📊 Tipo de datos: {data_type}")
else:
    print("⚠️  Configura los datos manualmente antes de continuar")

"""## 📊 Análisis de Datos

"""

# Función para encontrar y analizar datasets (Unificada con HerdNet)
def find_and_analyze_datasets():
    """Encontrar y analizar datasets disponibles según el tipo de datos"""

    if not data_path:
        print("❌ No hay ruta de datos configurada")
        return []

    datasets_found = []

    if data_type == "standard":
        # Estructura estándar COCO (igual que HerdNet)
        datasets_found = [TRAIN_ANN_FILE, VAL_ANN_FILE, TEST_ANN_FILE]
        print("📊 Usando datasets estándar COCO:")
        print(f"  Train: {TRAIN_ANN_FILE}")
        print(f"  Val: {VAL_ANN_FILE}")
        print(f"  Test: {TEST_ANN_FILE}")

    elif data_type == "groundtruth":
        # Estructura alternativa groundtruth
        datasets_found = [TRAIN_ANN_FILE_ALT, VAL_ANN_FILE_ALT, TEST_ANN_FILE_ALT]
        print("📊 Usando datasets groundtruth:")
        print(f"  Train: {TRAIN_ANN_FILE_ALT}")
        print(f"  Val: {VAL_ANN_FILE_ALT}")
        print(f"  Test: {TEST_ANN_FILE_ALT}")

    else:
        # Estructura legacy - buscar archivos JSON
        data_root = Path(data_path)
        json_patterns = [
            "**/train_*.json",
            "**/val_*.json",
            "**/test_*.json",
            "**/*_big_size_*.json",
            "**/*_subframes_*.json"
        ]

        for pattern in json_patterns:
            for json_file in data_root.glob(pattern):
                if json_file.is_file():
                    datasets_found.append(json_file)

        print(f"📊 Datasets encontrados en estructura legacy ({len(datasets_found)}):")
        for i, dataset in enumerate(datasets_found):
            print(f"  {i+1}. {dataset}")

    # Analizar el primer dataset encontrado
    if datasets_found:
        sample_data = analyze_dataset(datasets_found[0])
        return datasets_found

    return []

# Función para analizar un dataset COCO
def analyze_dataset(json_path):
    """Analizar estadísticas de un dataset COCO"""

    with open(json_path, 'r') as f:
        data = json.load(f)

    print(f"\n📈 Análisis de {json_path.name}:")
    print(f"  Imágenes: {len(data['images'])}")
    print(f"  Anotaciones: {len(data['annotations'])}")
    print(f"  Categorías: {len(data['categories'])}")

    # Estadísticas por categoría
    cat_counts = {}
    for ann in data['annotations']:
        cat_id = ann['category_id']
        cat_counts[cat_id] = cat_counts.get(cat_id, 0) + 1

    print("\n  Distribución por categoría:")
    for cat in data['categories']:
        count = cat_counts.get(cat['id'], 0)
        print(f"    {cat['name']}: {count}")

    return data

# Buscar y analizar datasets
datasets = find_and_analyze_datasets()



"""## ⚙️ Configuración del Entrenamiento"""

# Configuración del entrenamiento
class YOLOConfig:
    def __init__(self):
        # Parámetros del modelo - OPTIMIZADOS PARA VELOCIDAD
        self.model = 'yolov8s.pt'  # yolov8n.pt, yolov8s.pt, yolov8m.pt, yolov8l.pt, yolov8x.pt
        self.image_size = 512
        self.epochs = 100
        self.batch_size = 64  # AUMENTADO para mayor velocidad (ajustar según memoria)
        self.learning_rate = 0.01
        self.patience = 10
        self.device = 0  # GPU 0
        self.workers = 8  # AUMENTADO para mayor paralelización
        self.project = '/content/runs_yolo'
        self.name = 'yolo_aerial_wildlife_v1'
        self.fp16 = True  # Mixed precision

        # NUEVAS CONFIGURACIONES V1
        self.save_period = 3  # Guardar cada 5 épocas (más frecuente)
        self.drive_backup_period = 3  # Backup en Drive cada 10 épocas
        self.drive_backup_dir = '/content/drive/MyDrive/aerial-wildlife-count-results/yolo_v1'
        self.resume_training = True  # Permitir reanudar entrenamiento

        # Clases del dataset
        self.classes = [
            "Buffalo", "Elephant", "Kob",
            "Alcelaphinae", "Warthog", "Waterbuck"
        ]

    def print_config(self):
        print("🔧 Configuración YOLOv8 V1 (Optimizada):")
        print(f"  Modelo: {self.model}")
        print(f"  Tamaño de imagen: {self.image_size}")
        print(f"  Épocas: {self.epochs}")
        print(f"  Batch size: {self.batch_size} (OPTIMIZADO)")
        print(f"  Workers: {self.workers} (OPTIMIZADO)")
        print(f"  Learning rate: {self.learning_rate}")
        print(f"  Dispositivo: {self.device}")
        print(f"  Mixed precision: {self.fp16}")
        print(f"  Save period: {self.save_period} épocas")
        print(f"  Drive backup: {self.drive_backup_period} épocas")
        print(f"  Resume training: {self.resume_training}")

# Crear instancia de configuración
yolo_config = YOLOConfig()
yolo_config.print_config()

"""## 🔥 Funciones de Backup Automático en Drive

"""

# ============================================================
# FUNCIONES DE BACKUP AUTOMÁTICO EN DRIVE - V1 (TIEMPO REAL)
# ============================================================

import shutil
import time
from datetime import datetime
import threading
from ultralytics.utils.callbacks import default_callbacks

def create_drive_backup_dir():
    """Crear directorio de backup en Drive"""
    backup_dir = Path(yolo_config.drive_backup_dir)
    backup_dir.mkdir(parents=True, exist_ok=True)
    print(f"✅ Directorio de backup creado: {backup_dir}")
    return backup_dir

def backup_to_drive(epoch=None, force=False):
    """Hacer backup de checkpoints a Drive"""
    try:
        # Crear directorio de backup
        backup_dir = create_drive_backup_dir()

        # Directorio fuente (Colab)
        source_dir = Path(f"{yolo_config.project}/{yolo_config.name}")

        if not source_dir.exists():
            print("❌ No existe directorio de entrenamiento para hacer backup")
            return False

        # Crear subdirectorio con timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        if epoch is not None:
            backup_subdir = backup_dir / f"epoch_{epoch}_{timestamp}"
        else:
            backup_subdir = backup_dir / f"backup_{timestamp}"

        backup_subdir.mkdir(exist_ok=True)

        # Copiar archivos importantes
        files_to_backup = [
            "weights/",
            "results.png",
            "confusion_matrix.png",
            "results.csv",
            "train_batch*.jpg",
            "val_batch*.jpg"
        ]

        copied_files = 0
        for pattern in files_to_backup:
            try:
                for file_path in source_dir.glob(pattern):
                    if file_path.is_file():
                        dest_path = backup_subdir / file_path.name
                        shutil.copy2(file_path, dest_path)
                        copied_files += 1
                    elif file_path.is_dir():
                        dest_path = backup_subdir / file_path.name
                        shutil.copytree(file_path, dest_path, dirs_exist_ok=True)
                        copied_files += 1
            except Exception as e:
                print(f"⚠️ Error copiando {pattern}: {e}")

        print(f"✅ Backup completado: {copied_files} archivos copiados a {backup_subdir}")
        return True

    except Exception as e:
        print(f"❌ Error en backup: {e}")
        return False

# ============================================================
# CALLBACK PERSONALIZADO PARA BACKUP EN TIEMPO REAL
# ============================================================

class RealtimeBackupCallback:
    """Callback personalizado para backup en tiempo real durante el entrenamiento"""

    def __init__(self, backup_period=3):
        self.backup_period = backup_period
        self.last_backup_epoch = 0
        self.backup_dir = None

    def on_train_epoch_end(self, trainer):
        """Se ejecuta al final de cada época de entrenamiento"""
        try:
            current_epoch = trainer.epoch

            # Verificar si es momento de hacer backup
            if current_epoch - self.last_backup_epoch >= self.backup_period:
                print(f"🔄 Iniciando backup automático en tiempo real (época {current_epoch})...")

                # Crear directorio de backup si no existe
                if self.backup_dir is None:
                    self.backup_dir = create_drive_backup_dir()

                # Hacer backup inmediato
                if backup_to_drive(epoch=current_epoch):
                    self.last_backup_epoch = current_epoch

                    # Actualizar archivo de control
                    backup_file = Path(f"{yolo_config.drive_backup_dir}/last_backup_epoch.txt")
                    backup_file.parent.mkdir(parents=True, exist_ok=True)
                    with open(backup_file, 'w') as f:
                        f.write(str(current_epoch))

                    print(f"✅ Backup en tiempo real completado (época {current_epoch})")
                else:
                    print(f"❌ Error en backup en tiempo real (época {current_epoch})")

        except Exception as e:
            print(f"❌ Error en callback de backup: {e}")

    def on_val_end(self, validator):
        """Se ejecuta al final de la validación"""
        try:
            # Obtener la época actual del trainer asociado al validator
            current_epoch = getattr(validator, 'epoch', None)
            if current_epoch is None and hasattr(validator, 'trainer'):
                current_epoch = getattr(validator.trainer, 'epoch', None)
            
            # Si no podemos obtener la época, usar un valor por defecto
            if current_epoch is None:
                current_epoch = "unknown"
                print("⚠️ No se pudo obtener el número de época para backup")
                return

            # Backup del best model si es mejor que el anterior
            if hasattr(validator, 'best_fitness') and validator.best_fitness is not None:
                print(f"📊 Época {current_epoch}: Mejor fitness = {validator.best_fitness:.4f}")

                # Backup del best model cada vez que mejora
                if backup_to_drive(epoch=f"best_{current_epoch}"):
                    print(f"✅ Best model backup completado (época {current_epoch})")

        except Exception as e:
            print(f"❌ Error en backup de best model: {e}")

# ============================================================
# FUNCIONES DE BACKUP LEGACY (MANTENIDAS PARA COMPATIBILIDAD)
# ============================================================

def auto_backup_thread():
    """Thread para backup automático cada X épocas (LEGACY - NO USAR)"""
    global backup_thread_running
    backup_thread_running = True

    print("🔄 Thread de backup automático iniciado (LEGACY)")

    while backup_thread_running:
        try:
            # Verificar si hay nuevos checkpoints
            weights_dir = Path(f"{yolo_config.project}/{yolo_config.name}/weights")
            if weights_dir.exists():
                checkpoints = list(weights_dir.glob("*.pt"))
                if checkpoints:
                    # Obtener el checkpoint más reciente
                    latest_checkpoint = max(checkpoints, key=lambda x: x.stat().st_mtime)

                    # Verificar si necesita backup
                    backup_file = Path(f"{yolo_config.drive_backup_dir}/last_backup_epoch.txt")
                    last_backup_epoch = 0

                    if backup_file.exists():
                        try:
                            with open(backup_file, 'r') as f:
                                last_backup_epoch = int(f.read().strip())
                        except:
                            last_backup_epoch = 0

                    # Extraer época del nombre del archivo
                    current_epoch = 0
                    if "epoch" in latest_checkpoint.name:
                        try:
                            current_epoch = int(latest_checkpoint.name.split("epoch_")[1].split(".")[0])
                        except:
                            current_epoch = 0

                    # Hacer backup si ha pasado el período configurado
                    if current_epoch - last_backup_epoch >= yolo_config.drive_backup_period:
                        print(f"🔄 Iniciando backup automático (época {current_epoch})...")
                        if backup_to_drive(epoch=current_epoch):
                            # Actualizar archivo de control
                            backup_file.parent.mkdir(parents=True, exist_ok=True)
                            with open(backup_file, 'w') as f:
                                f.write(str(current_epoch))
                            print(f"✅ Backup automático completado (época {current_epoch})")

            # Esperar 5 minutos antes de verificar nuevamente
            time.sleep(300)  # 5 minutos

        except Exception as e:
            print(f"❌ Error en backup automático: {e}")
            time.sleep(60)  # Esperar 1 minuto en caso de error

    print("🛑 Thread de backup automático detenido")

def start_auto_backup():
    """Iniciar backup automático en segundo plano (LEGACY - NO USAR)"""
    global backup_thread, backup_thread_running

    # Detener thread anterior si existe
    if backup_thread_running:
        stop_auto_backup()
        time.sleep(2)  # Esperar a que se detenga

    backup_thread_running = False

    # Verificar si ya hay un thread corriendo
    if 'backup_thread' in globals() and backup_thread is not None and backup_thread.is_alive():
        print("⚠️ Backup automático ya está ejecutándose")
        return

    backup_thread = threading.Thread(target=auto_backup_thread, daemon=True)
    backup_thread.start()
    print("🚀 Backup automático iniciado en segundo plano")

def stop_auto_backup():
    """Detener backup automático (LEGACY - NO USAR)"""
    global backup_thread_running
    backup_thread_running = False
    print("🛑 Backup automático detenido")

def resume_training_from_drive():
    """Reanudar entrenamiento desde el último checkpoint en Drive"""
    try:
        backup_dir = Path(yolo_config.drive_backup_dir)
        if not backup_dir.exists():
            print("❌ No hay backups disponibles en Drive")
            return None

        # Buscar el backup más reciente
        backup_dirs = [d for d in backup_dir.iterdir() if d.is_dir() and "epoch_" in d.name]
        if not backup_dirs:
            print("❌ No se encontraron backups con checkpoints")
            return None

        # Ordenar por fecha de modificación
        latest_backup = max(backup_dirs, key=lambda x: x.stat().st_mtime)

        # Buscar el mejor checkpoint
        weights_dir = latest_backup / "weights"
        if weights_dir.exists():
            checkpoints = list(weights_dir.glob("*.pt"))
            if checkpoints:
                # Priorizar best.pt, luego el más reciente
                best_checkpoint = None
                for ckpt in checkpoints:
                    if "best" in ckpt.name:
                        best_checkpoint = ckpt
                        break

                if not best_checkpoint:
                    best_checkpoint = max(checkpoints, key=lambda x: x.stat().st_mtime)

                print(f"✅ Checkpoint encontrado para reanudar: {best_checkpoint}")
                return str(best_checkpoint)

        print("❌ No se encontró checkpoint válido en backups")
        return None

    except Exception as e:
        print(f"❌ Error al buscar checkpoint para reanudar: {e}")
        return None

print("✅ Funciones de backup automático cargadas")

"""## 📊 Funciones de Monitoreo en Tiempo Real

"""

# ============================================================
# FUNCIONES DE MONITOREO EN TIEMPO REAL
# ============================================================

def monitor_training_progress():
    """Monitorear el progreso del entrenamiento en tiempo real"""
    try:
        results_dir = Path(f"{yolo_config.project}/{yolo_config.name}")

        if not results_dir.exists():
            print("❌ Directorio de resultados no encontrado")
            return

        # Verificar archivos de resultados
        results_csv = results_dir / "results.csv"
        if results_csv.exists():
            import pandas as pd
            df = pd.read_csv(results_csv)
            if not df.empty:
                latest_epoch = df.iloc[-1]
                print(f"📊 Progreso actual:")
                print(f"  Época: {latest_epoch.get('epoch', 'N/A')}")
                print(f"  mAP: {latest_epoch.get('metrics/mAP50(B)', 'N/A'):.4f}")
                print(f"  Loss: {latest_epoch.get('train/box_loss', 'N/A'):.4f}")
                print(f"  Val Loss: {latest_epoch.get('val/box_loss', 'N/A'):.4f}")

        # Verificar checkpoints
        weights_dir = results_dir / "weights"
        if weights_dir.exists():
            checkpoints = list(weights_dir.glob("*.pt"))
            print(f"📁 Checkpoints disponibles: {len(checkpoints)}")
            for ckpt in checkpoints:
                size_mb = ckpt.stat().st_size / (1024 * 1024)
                print(f"  - {ckpt.name} ({size_mb:.1f} MB)")

        # Verificar backups en Drive
        backup_dir = Path(yolo_config.drive_backup_dir)
        if backup_dir.exists():
            backups = list(backup_dir.glob("epoch_*"))
            print(f"💾 Backups en Drive: {len(backups)}")

    except Exception as e:
        print(f"❌ Error en monitoreo: {e}")

def get_training_status():
    """Obtener estado actual del entrenamiento"""
    try:
        results_dir = Path(f"{yolo_config.project}/{yolo_config.name}")

        if not results_dir.exists():
            return "No iniciado"

        # Verificar si hay resultados
        results_csv = results_dir / "results.csv"
        if results_csv.exists():
            import pandas as pd
            df = pd.read_csv(results_csv)
            if not df.empty:
                latest_epoch = df.iloc[-1]['epoch']
                total_epochs = yolo_config.epochs
                progress = (latest_epoch / total_epochs) * 100
                return f"En progreso: {latest_epoch}/{total_epochs} épocas ({progress:.1f}%)"

        return "Iniciando"

    except Exception as e:
        return f"Error: {e}"

def estimate_remaining_time():
    """Estimar tiempo restante de entrenamiento"""
    try:
        results_dir = Path(f"{yolo_config.project}/{yolo_config.name}")
        results_csv = results_dir / "results.csv"

        if not results_csv.exists():
            return "No disponible"

        import pandas as pd
        df = pd.read_csv(results_csv)

        if len(df) < 2:
            return "Calculando..."

        # Calcular tiempo promedio por época basado en el número de épocas
        # Asumir que cada época toma aproximadamente el mismo tiempo
        current_epoch = df.iloc[-1]['epoch']
        remaining_epochs = yolo_config.epochs - current_epoch

        # Estimación simple: asumir 2-5 minutos por época
        estimated_minutes = remaining_epochs * 3  # 3 minutos promedio por época

        if estimated_minutes < 60:
            return f"Tiempo estimado restante: {estimated_minutes:.0f} minutos"
        else:
            hours = estimated_minutes / 60
            return f"Tiempo estimado restante: {hours:.1f} horas"

    except Exception as e:
        return f"Error: {e}"

def show_training_status():
    """Mostrar estado completo del entrenamiento"""
    print("=" * 60)
    print("📊 ESTADO DEL ENTRENAMIENTO YOLOv8 V1")
    print("=" * 60)
    print(f"Estado: {get_training_status()}")
    print(f"Tiempo restante: {estimate_remaining_time()}")
    print()
    monitor_training_progress()
    print("=" * 60)

# ============================================================
# CALLBACK DE MONITOREO DURANTE EL ENTRENAMIENTO
# ============================================================

class TrainingMonitorCallback:
    """Callback para monitorear el entrenamiento en tiempo real"""

    def __init__(self, monitor_period=5):
        self.monitor_period = monitor_period
        self.last_monitor_epoch = 0

    def on_train_epoch_end(self, trainer):
        """Se ejecuta al final de cada época de entrenamiento"""
        try:
            current_epoch = trainer.epoch

            # Monitorear cada X épocas
            if current_epoch - self.last_monitor_epoch >= self.monitor_period:
                print(f"\n📊 MONITOREO ÉPOCA {current_epoch}:")
                print(f"  Loss: {trainer.loss:.4f}")
                if hasattr(trainer, 'metrics') and trainer.metrics:
                    print(f"  mAP@0.5: {trainer.metrics.get('mAP50', 'N/A')}")
                    print(f"  Precision: {trainer.metrics.get('precision', 'N/A')}")
                    print(f"  Recall: {trainer.metrics.get('recall', 'N/A')}")

                # Mostrar progreso
                progress = (current_epoch / yolo_config.epochs) * 100
                print(f"  Progreso: {current_epoch}/{yolo_config.epochs} épocas ({progress:.1f}%)")

                self.last_monitor_epoch = current_epoch

        except Exception as e:
            print(f"❌ Error en callback de monitoreo: {e}")

    def on_val_end(self, validator):
        """Se ejecuta al final de la validación"""
        try:
            # Obtener la época actual del trainer asociado al validator
            current_epoch = getattr(validator, 'epoch', None)
            if current_epoch is None and hasattr(validator, 'trainer'):
                current_epoch = getattr(validator.trainer, 'epoch', None)
            
            # Si no podemos obtener la época, usar un valor por defecto
            if current_epoch is None:
                current_epoch = "unknown"

            if hasattr(validator, 'metrics') and validator.metrics:
                print(f"📈 Época {current_epoch} - Validación completada")
                print(f"  mAP@0.5: {validator.metrics.get('mAP50', 'N/A'):.4f}")
                print(f"  mAP@0.5:0.95: {validator.metrics.get('mAP50-95', 'N/A'):.4f}")

        except Exception as e:
            print(f"❌ Error en callback de validación: {e}")

print("✅ Funciones de monitoreo en tiempo real cargadas")

"""## 🔄 Conversión de Datos COCO a YOLO

"""

# Función para convertir COCO a YOLO
def coco_to_yolo(coco_json_path, images_dir, output_dir, class_names):
    """Convierte anotaciones COCO a formato YOLO"""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Leer archivo COCO
    with open(coco_json_path, 'r') as f:
        coco_data = json.load(f)

    # Crear mapeo de categorías
    cat_id_to_class = {cat['id']: cat['name'] for cat in coco_data['categories']}
    class_to_id = {name: idx for idx, name in enumerate(class_names)}

    # Crear mapeo de imágenes
    img_id_to_info = {img['id']: img for img in coco_data['images']}

    # Procesar anotaciones
    annotations_by_image = {}
    for ann in coco_data['annotations']:
        img_id = ann['image_id']
        if img_id not in annotations_by_image:
            annotations_by_image[img_id] = []
        annotations_by_image[img_id].append(ann)

    # Convertir cada imagen
    for img_id, img_info in tqdm(img_id_to_info.items(), desc="Convirtiendo a YOLO"):
        img_name = img_info['file_name']
        img_width = img_info['width']
        img_height = img_info['height']

        # Crear archivo de anotación YOLO
        txt_name = Path(img_name).stem + '.txt'
        txt_path = output_dir / txt_name

        with open(txt_path, 'w') as f:
            if img_id in annotations_by_image:
                for ann in annotations_by_image[img_id]:
                    cat_name = cat_id_to_class[ann['category_id']]
                    if cat_name in class_to_id:
                        class_id = class_to_id[cat_name]

                        # Convertir bbox [x, y, w, h] a [center_x, center_y, w, h] normalizado
                        x, y, w, h = ann['bbox']
                        center_x = (x + w/2) / img_width
                        center_y = (y + h/2) / img_height
                        norm_w = w / img_width
                        norm_h = h / img_height

                        f.write(f"{class_id} {center_x:.6f} {center_y:.6f} {norm_w:.6f} {norm_h:.6f}\n")

    print(f"✅ Convertido {len(img_id_to_info)} imágenes a formato YOLO")
    return output_dir

# Preparar datos para conversión (Unificado con HerdNet)
def prepare_yolo_data():
    """Preparar datos para entrenamiento YOLO según el tipo de datos"""

    if data_type == "standard":
        # Usar rutas estándar COCO (igual que HerdNet)
        train_json = TRAIN_ANN_FILE
        val_json = VAL_ANN_FILE
        test_json = TEST_ANN_FILE

        # Verificar que existan
        if not all([train_json.exists(), val_json.exists()]):
            print("❌ Faltan archivos de datos estándar COCO")
            return None, None, None

    elif data_type == "groundtruth":
        # Usar rutas groundtruth
        train_json = TRAIN_ANN_FILE_ALT
        val_json = VAL_ANN_FILE_ALT
        test_json = TEST_ANN_FILE_ALT

        # Verificar que existan
        if not all([train_json.exists(), val_json.exists()]):
            print("❌ Faltan archivos de datos groundtruth")
            return None, None, None

    else:
        # Estructura legacy - buscar en datasets encontrados
        if not datasets:
            print("❌ No hay datasets disponibles")
            return None, None, None

        # Buscar archivos de datos
        train_files = [d for d in datasets if 'train' in d.name.lower()]
        val_files = [d for d in datasets if 'val' in d.name.lower()]
        test_files = [d for d in datasets if 'test' in d.name.lower()]

        train_json = train_files[0] if train_files else None
        val_json = val_files[0] if val_files else None
        test_json = test_files[0] if test_files else None

        if not all([train_json, val_json]):
            print("❌ Faltan archivos de datos. Necesitas al menos train y val JSON files.")
            return None, None, None

    print(f"✅ Archivos seleccionados:")
    print(f"  Train: {train_json}")
    print(f"  Val: {val_json}")
    if test_json and test_json.exists():
        print(f"  Test: {test_json}")

    return train_json, val_json, test_json

# Preparar datos
train_json, val_json, test_json = prepare_yolo_data()

if train_json and val_json:
    print("✅ Datos preparados para conversión")
else:
    print("❌ Error preparando datos")

# Convertir datos si están disponibles (ANTES del entrenamiento)
if train_json and val_json:

    # Determinar directorios de imágenes según el tipo de datos
    if data_type == "standard":
        train_img_dir = TRAIN_IMG_DIR
        val_img_dir = VAL_IMG_DIR
        test_img_dir = TEST_IMG_DIR
    elif data_type == "groundtruth":
        train_img_dir = TRAIN_IMG_DIR_ALT
        val_img_dir = VAL_IMG_DIR_ALT
        test_img_dir = TEST_IMG_DIR_ALT
    else:
        # Estructura legacy
        train_img_dir = train_json.parent / "images" if (train_json.parent / "images").exists() else train_json.parent.parent / "train"
        val_img_dir = val_json.parent.parent / "val"
        test_img_dir = None

    # Convertir datos de entrenamiento
    print("🔄 Convirtiendo datos de entrenamiento...")
    train_yolo_dir = coco_to_yolo(
        train_json,
        train_img_dir,
        '/content/yolo_data/train/labels',
        yolo_config.classes
    )

    # Convertir datos de validación
    print("🔄 Convirtiendo datos de validación...")
    val_yolo_dir = coco_to_yolo(
        val_json,
        val_img_dir,
        '/content/yolo_data/val/labels',
        yolo_config.classes
    )

    # Crear directorios de imágenes
    os.makedirs('/content/yolo_data/train/images', exist_ok=True)
    os.makedirs('/content/yolo_data/val/images', exist_ok=True)

    # Copiar imágenes
    print("📁 Copiando imágenes...")
    for img_file in tqdm(os.listdir(train_img_dir)):
        if img_file.lower().endswith(('.jpg', '.jpeg', '.png')):
            src = os.path.join(train_img_dir, img_file)
            dst = os.path.join('/content/yolo_data/train/images', img_file)
            if os.path.exists(src):
                shutil.copy2(src, dst)

    for img_file in tqdm(os.listdir(val_img_dir)):
        if img_file.lower().endswith(('.jpg', '.jpeg', '.png')):
            src = os.path.join(val_img_dir, img_file)
            dst = os.path.join('/content/yolo_data/val/images', img_file)
            if os.path.exists(src):
                shutil.copy2(src, dst)

    # Copiar imágenes de test si están disponibles
    if test_img_dir and test_img_dir.exists():
        print("📁 Copiando imágenes de test...")
        os.makedirs('/content/yolo_data/test/images', exist_ok=True)
        for img_file in tqdm(os.listdir(test_img_dir)):
            if img_file.lower().endswith(('.jpg', '.jpeg', '.png')):
                src = os.path.join(test_img_dir, img_file)
                dst = os.path.join('/content/yolo_data/test/images', img_file)
                if os.path.exists(src):
                    shutil.copy2(src, dst)

    # Crear archivo de configuración YOLO
    test_line = "test: test/images\n" if test_img_dir and test_img_dir.exists() else ""
    yolo_config_content = f"""# Dataset configuration for YOLOv8
path: /content/yolo_data
train: train/images
val: val/images
{test_line}
# Classes
nc: {len(yolo_config.classes)}
names: {yolo_config.classes}
"""

    with open('/content/yolo_data/dataset.yaml', 'w') as f:
        f.write(yolo_config_content)

    print("✅ Conversión completada")
    print(f"📊 Imágenes de entrenamiento: {len(os.listdir('/content/yolo_data/train/images'))}")
    print(f"📊 Imágenes de validación: {len(os.listdir('/content/yolo_data/val/images'))}")
    if test_img_dir and test_img_dir.exists():
        print(f"📊 Imágenes de test: {len(os.listdir('/content/yolo_data/test/images'))}")

else:
    print("❌ No se puede convertir sin datos válidos")

"""## 🚀 Entrenamiento Optimizado con Backup Automático

"""

# Entrenar modelo YOLOv8 V1 con backup automático EN TIEMPO REAL
if train_json and val_json:

    print("🚀 Iniciando entrenamiento YOLOv8 V1 (Optimizado con Backup en Tiempo Real)...")
    print("🔥 Características V1:")
    print(f"  - Batch size optimizado: {yolo_config.batch_size}")
    print(f"  - Workers optimizados: {yolo_config.workers}")
    print(f"  - Guardado cada {yolo_config.save_period} épocas")
    print(f"  - Backup en Drive cada {yolo_config.drive_backup_period} épocas (TIEMPO REAL)")
    print(f"  - Recuperación automática: {yolo_config.resume_training}")
    print("🔥 NUEVO: Backup automático en tiempo real durante el entrenamiento")

    # Inicializar modelo
    model = YOLO(yolo_config.model)

    # Crear callbacks para backup y monitoreo en tiempo real
    backup_callback = RealtimeBackupCallback(backup_period=yolo_config.drive_backup_period)
    monitor_callback = TrainingMonitorCallback(monitor_period=5)  # Monitorear cada 5 épocas

    print(f"✅ Callback de backup en tiempo real creado (cada {yolo_config.drive_backup_period} épocas)")
    print(f"✅ Callback de monitoreo en tiempo real creado (cada 5 épocas)")

    # Configurar parámetros de entrenamiento - OPTIMIZADOS V1
    train_args = {
        'data': '/content/yolo_data/dataset.yaml',
        'epochs': yolo_config.epochs,
        'imgsz': yolo_config.image_size,
        'batch': yolo_config.batch_size,
        'device': yolo_config.device,
        'workers': yolo_config.workers,
        'project': yolo_config.project,
        'name': yolo_config.name,
        'patience': yolo_config.patience,
        'lr0': yolo_config.learning_rate,
        'amp': yolo_config.fp16,
        'save': True,
        'save_period': yolo_config.save_period,  # Consistente: 5 épocas
        'val': True,
        'plots': True,
        'verbose': True,
    }

    # Verificar si hay checkpoint para reanudar
    resume_path = None
    if yolo_config.resume_training:
        # Buscar en Colab primero
        weights_dir = Path(f"{yolo_config.project}/{yolo_config.name}/weights")
        if weights_dir.exists():
            checkpoints = list(weights_dir.glob("*.pt"))
            if checkpoints:
                resume_path = str(max(checkpoints, key=lambda x: x.stat().st_mtime))
                print(f"🔄 Reanudando desde checkpoint local: {resume_path}")
        else:
            # Buscar en Drive
            resume_path = resume_training_from_drive()
            if resume_path:
                print(f"🔄 Reanudando desde checkpoint en Drive: {resume_path}")

    if resume_path:
        train_args['resume'] = resume_path

    print("📋 Parámetros de entrenamiento:")
    for key, value in train_args.items():
        print(f"  {key}: {value}")

    # NO usar el thread de backup legacy - usar callback en tiempo real
    print("🔄 Usando sistema de backup en tiempo real (NO thread legacy)")

    # Iniciar entrenamiento con callbacks de backup y monitoreo
    print("🚀 Iniciando entrenamiento con backup y monitoreo en tiempo real...")

    # Registrar los callbacks personalizados
    model.add_callback('on_train_epoch_end', backup_callback.on_train_epoch_end)
    model.add_callback('on_val_end', backup_callback.on_val_end)

    # Registrar callback de monitoreo
    model.add_callback('on_train_epoch_end', monitor_callback.on_train_epoch_end)
    model.add_callback('on_val_end', monitor_callback.on_val_end)

    # Iniciar entrenamiento
    results = model.train(**train_args)

    print("✅ Entrenamiento completado!")
    print(f"📁 Resultados guardados en: {yolo_config.project}/{yolo_config.name}")

    # Hacer backup final
    print("🔄 Realizando backup final...")
    backup_to_drive(epoch="final")

"""## 📊 Métricas de Clasificación Detalladas

"""

# ============================================================
# FUNCIONES PARA MÉTRICAS DE CLASIFICACIÓN DETALLADAS
# ============================================================

import numpy as np
from sklearn.metrics import precision_recall_fscore_support, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

def calculate_detailed_metrics(model, dataset_path, conf_threshold=0.5, iou_threshold=0.5):
    """Calcular métricas detalladas de clasificación para cada clase"""

    try:
        print("🔄 Calculando métricas detalladas de clasificación...")

        # Realizar validación con el modelo
        results = model.val(data=dataset_path, conf=conf_threshold, iou=iou_threshold, verbose=False)

        # Obtener métricas del modelo
        metrics = results.results_dict

        # Crear diccionario de métricas por clase
        class_metrics = {}

        # Obtener nombres de las clases
        class_names = yolo_config.classes

        # Calcular métricas para cada clase
        for i, class_name in enumerate(class_names):
            # Obtener métricas específicas de la clase (si están disponibles)
            precision_key = f'metrics/precision(B)_{i}'
            recall_key = f'metrics/recall(B)_{i}'
            f1_key = f'metrics/f1(B)_{i}'

            class_metrics[class_name] = {
                'precision': metrics.get(precision_key, 0.0),
                'recall': metrics.get(recall_key, 0.0),
                'f1': metrics.get(f1_key, 0.0),
                'class_id': i
            }

        # Métricas generales
        general_metrics = {
            'mAP50': metrics.get('metrics/mAP50(B)', 0.0),
            'mAP50-95': metrics.get('metrics/mAP50-95(B)', 0.0),
            'precision': metrics.get('metrics/precision(B)', 0.0),
            'recall': metrics.get('metrics/recall(B)', 0.0),
            'f1': metrics.get('metrics/f1(B)', 0.0)
        }

        return class_metrics, general_metrics, results

    except Exception as e:
        print(f"❌ Error calculando métricas detalladas: {e}")
        return {}, {}, None

def create_classification_report(class_metrics, general_metrics, save_path=None):
    """Crear reporte detallado de clasificación"""

    print("\n" + "="*80)
    print("📊 REPORTE DETALLADO DE MÉTRICAS DE CLASIFICACIÓN")
    print("="*80)

    # Métricas generales
    print("\n🎯 MÉTRICAS GENERALES:")
    print(f"  mAP@0.5:     {general_metrics.get('mAP50', 0.0):.4f}")
    print(f"  mAP@0.5:0.95: {general_metrics.get('mAP50-95', 0.0):.4f}")
    print(f"  Precision:   {general_metrics.get('precision', 0.0):.4f}")
    print(f"  Recall:      {general_metrics.get('recall', 0.0):.4f}")
    print(f"  F1-Score:    {general_metrics.get('f1', 0.0):.4f}")

    # Métricas por clase
    print("\n📋 MÉTRICAS POR CLASE:")
    print("-" * 60)
    print(f"{'Clase':<15} {'Precision':<10} {'Recall':<10} {'F1-Score':<10}")
    print("-" * 60)

    for class_name, metrics in class_metrics.items():
        print(f"{class_name:<15} {metrics['precision']:<10.4f} {metrics['recall']:<10.4f} {metrics['f1']:<10.4f}")

    # Guardar reporte si se especifica ruta
    if save_path:
        with open(save_path, 'w') as f:
            f.write("REPORTE DETALLADO DE MÉTRICAS DE CLASIFICACIÓN\n")
            f.write("="*50 + "\n\n")

            f.write("MÉTRICAS GENERALES:\n")
            f.write(f"mAP@0.5:     {general_metrics.get('mAP50', 0.0):.4f}\n")
            f.write(f"mAP@0.5:0.95: {general_metrics.get('mAP50-95', 0.0):.4f}\n")
            f.write(f"Precision:   {general_metrics.get('precision', 0.0):.4f}\n")
            f.write(f"Recall:      {general_metrics.get('recall', 0.0):.4f}\n")
            f.write(f"F1-Score:    {general_metrics.get('f1', 0.0):.4f}\n\n")

            f.write("MÉTRICAS POR CLASE:\n")
            f.write("-" * 60 + "\n")
            f.write(f"{'Clase':<15} {'Precision':<10} {'Recall':<10} {'F1-Score':<10}\n")
            f.write("-" * 60 + "\n")

            for class_name, metrics in class_metrics.items():
                f.write(f"{class_name:<15} {metrics['precision']:<10.4f} {metrics['recall']:<10.4f} {metrics['f1']:<10.4f}\n")

        print(f"\n✅ Reporte guardado en: {save_path}")

    return class_metrics, general_metrics

def plot_class_metrics(class_metrics, save_path=None):
    """Crear gráficos de métricas por clase"""

    try:
        # Preparar datos para gráficos
        classes = list(class_metrics.keys())
        precisions = [class_metrics[cls]['precision'] for cls in classes]
        recalls = [class_metrics[cls]['recall'] for cls in classes]
        f1_scores = [class_metrics[cls]['f1'] for cls in classes]

        # Crear figura con subplots
        fig, axes = plt.subplots(2, 2, figsize=(15, 12))
        fig.suptitle('Métricas de Clasificación por Clase', fontsize=16, fontweight='bold')

        # Gráfico de barras - Precision
        axes[0, 0].bar(classes, precisions, color='skyblue', alpha=0.7)
        axes[0, 0].set_title('Precision por Clase')
        axes[0, 0].set_ylabel('Precision')
        axes[0, 0].tick_params(axis='x', rotation=45)
        axes[0, 0].grid(True, alpha=0.3)

        # Gráfico de barras - Recall
        axes[0, 1].bar(classes, recalls, color='lightgreen', alpha=0.7)
        axes[0, 1].set_title('Recall por Clase')
        axes[0, 1].set_ylabel('Recall')
        axes[0, 1].tick_params(axis='x', rotation=45)
        axes[0, 1].grid(True, alpha=0.3)

        # Gráfico de barras - F1-Score
        axes[1, 0].bar(classes, f1_scores, color='lightcoral', alpha=0.7)
        axes[1, 0].set_title('F1-Score por Clase')
        axes[1, 0].set_ylabel('F1-Score')
        axes[1, 0].tick_params(axis='x', rotation=45)
        axes[1, 0].grid(True, alpha=0.3)

        # Gráfico combinado
        x = np.arange(len(classes))
        width = 0.25

        axes[1, 1].bar(x - width, precisions, width, label='Precision', alpha=0.7)
        axes[1, 1].bar(x, recalls, width, label='Recall', alpha=0.7)
        axes[1, 1].bar(x + width, f1_scores, width, label='F1-Score', alpha=0.7)

        axes[1, 1].set_title('Comparación de Métricas por Clase')
        axes[1, 1].set_ylabel('Score')
        axes[1, 1].set_xticks(x)
        axes[1, 1].set_xticklabels(classes, rotation=45)
        axes[1, 1].legend()
        axes[1, 1].grid(True, alpha=0.3)

        plt.tight_layout()

        # Guardar gráfico si se especifica ruta
        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"✅ Gráfico de métricas guardado en: {save_path}")

        plt.show()

    except Exception as e:
        print(f"❌ Error creando gráficos de métricas: {e}")

def create_metrics_summary_table(class_metrics, general_metrics):
    """Crear tabla resumen de métricas"""

    print("\n" + "="*80)
    print("📊 TABLA RESUMEN DE MÉTRICAS")
    print("="*80)

    # Crear DataFrame para mejor visualización
    import pandas as pd

    # Datos por clase
    class_data = []
    for class_name, metrics in class_metrics.items():
        class_data.append({
            'Clase': class_name,
            'Precision': f"{metrics['precision']:.4f}",
            'Recall': f"{metrics['recall']:.4f}",
            'F1-Score': f"{metrics['f1']:.4f}"
        })

    # Agregar métricas generales
    class_data.append({
        'Clase': 'PROMEDIO',
        'Precision': f"{general_metrics.get('precision', 0.0):.4f}",
        'Recall': f"{general_metrics.get('recall', 0.0):.4f}",
        'F1-Score': f"{general_metrics.get('f1', 0.0):.4f}"
    })

    df = pd.DataFrame(class_data)
    print(df.to_string(index=False))

    return df

def save_metrics_to_csv(class_metrics, general_metrics, save_path):
    """Guardar métricas en archivo CSV"""

    try:
        import pandas as pd

        # Preparar datos
        data = []
        for class_name, metrics in class_metrics.items():
            data.append({
                'Clase': class_name,
                'Precision': metrics['precision'],
                'Recall': metrics['recall'],
                'F1-Score': metrics['f1'],
                'Tipo': 'Clase_Individual'
            })

        # Agregar métricas generales
        data.append({
            'Clase': 'GENERAL',
            'Precision': general_metrics.get('precision', 0.0),
            'Recall': general_metrics.get('recall', 0.0),
            'F1-Score': general_metrics.get('f1', 0.0),
            'Tipo': 'Promedio_General'
        })

        # Crear DataFrame y guardar
        df = pd.DataFrame(data)
        df.to_csv(save_path, index=False)
        print(f"✅ Métricas guardadas en CSV: {save_path}")

        return df

    except Exception as e:
        print(f"❌ Error guardando métricas en CSV: {e}")
        return None

def calculate_metrics_with_thresholds(model, dataset_path, thresholds=[0.3, 0.5, 0.7, 0.9]):
    """Calcular métricas con diferentes umbrales de confianza"""

    print("\n" + "="*80)
    print("📊 ANÁLISIS DE MÉTRICAS CON DIFERENTES UMBRALES DE CONFIANZA")
    print("="*80)

    results_summary = []

    for threshold in thresholds:
        print(f"\n🔄 Calculando métricas con threshold = {threshold}")

        class_metrics, general_metrics, _ = calculate_detailed_metrics(
            model, dataset_path, conf_threshold=threshold, iou_threshold=0.5
        )

        if class_metrics and general_metrics:
            results_summary.append({
                'threshold': threshold,
                'mAP50': general_metrics.get('mAP50', 0.0),
                'precision': general_metrics.get('precision', 0.0),
                'recall': general_metrics.get('recall', 0.0),
                'f1': general_metrics.get('f1', 0.0)
            })

            print(f"  mAP@0.5: {general_metrics.get('mAP50', 0.0):.4f}")
            print(f"  Precision: {general_metrics.get('precision', 0.0):.4f}")
            print(f"  Recall: {general_metrics.get('recall', 0.0):.4f}")
            print(f"  F1-Score: {general_metrics.get('f1', 0.0):.4f}")

    # Crear gráfico de métricas vs threshold
    if results_summary:
        import pandas as pd
        df_thresholds = pd.DataFrame(results_summary)

        plt.figure(figsize=(12, 8))

        plt.subplot(2, 2, 1)
        plt.plot(df_thresholds['threshold'], df_thresholds['mAP50'], 'o-', linewidth=2, markersize=8)
        plt.title('mAP@0.5 vs Threshold')
        plt.xlabel('Confidence Threshold')
        plt.ylabel('mAP@0.5')
        plt.grid(True, alpha=0.3)

        plt.subplot(2, 2, 2)
        plt.plot(df_thresholds['threshold'], df_thresholds['precision'], 'o-', linewidth=2, markersize=8, color='green')
        plt.title('Precision vs Threshold')
        plt.xlabel('Confidence Threshold')
        plt.ylabel('Precision')
        plt.grid(True, alpha=0.3)

        plt.subplot(2, 2, 3)
        plt.plot(df_thresholds['threshold'], df_thresholds['recall'], 'o-', linewidth=2, markersize=8, color='red')
        plt.title('Recall vs Threshold')
        plt.xlabel('Confidence Threshold')
        plt.ylabel('Recall')
        plt.grid(True, alpha=0.3)

        plt.subplot(2, 2, 4)
        plt.plot(df_thresholds['threshold'], df_thresholds['f1'], 'o-', linewidth=2, markersize=8, color='purple')
        plt.title('F1-Score vs Threshold')
        plt.xlabel('Confidence Threshold')
        plt.ylabel('F1-Score')
        plt.grid(True, alpha=0.3)

        plt.tight_layout()

        # Guardar gráfico
        threshold_plot_path = f"{yolo_config.project}/{yolo_config.name}/metrics_vs_threshold.png"
        plt.savefig(threshold_plot_path, dpi=300, bbox_inches='tight')
        print(f"\n✅ Gráfico de métricas vs threshold guardado en: {threshold_plot_path}")
        plt.show()

        # Guardar datos en CSV
        threshold_csv_path = f"{yolo_config.project}/{yolo_config.name}/metrics_vs_threshold.csv"
        df_thresholds.to_csv(threshold_csv_path, index=False)
        print(f"✅ Datos de métricas vs threshold guardados en: {threshold_csv_path}")

        return df_thresholds

    return None

def create_comprehensive_metrics_report():
    """Crear reporte comprensivo de todas las métricas"""

    print("\n" + "="*80)
    print("📋 CREANDO REPORTE COMPRENSIVO DE MÉTRICAS")
    print("="*80)

    try:
        # Cargar modelo
        best_model_path = f"{yolo_config.project}/{yolo_config.name}/weights/best.pt"
        if not os.path.exists(best_model_path):
            print("❌ No se encontró el modelo entrenado")
            return

        model = YOLO(best_model_path)

        # 1. Métricas con threshold por defecto
        print("\n1️⃣ Calculando métricas con threshold por defecto (0.5)...")
        class_metrics, general_metrics, _ = calculate_detailed_metrics(
            model, '/content/yolo_data/dataset.yaml', conf_threshold=0.5
        )

        if class_metrics and general_metrics:
            # Crear reporte detallado
            report_path = f"{yolo_config.project}/{yolo_config.name}/comprehensive_metrics_report.txt"
            create_classification_report(class_metrics, general_metrics, save_path=report_path)

            # Crear gráficos
            plot_path = f"{yolo_config.project}/{yolo_config.name}/comprehensive_class_metrics.png"
            plot_class_metrics(class_metrics, save_path=plot_path)

            # 2. Análisis con diferentes thresholds
            print("\n2️⃣ Analizando métricas con diferentes thresholds...")
            df_thresholds = calculate_metrics_with_thresholds(model, '/content/yolo_data/dataset.yaml')

            # 3. Análisis de rendimiento por clase
            print("\n3️⃣ Analizando rendimiento por clase...")
            analyze_class_performance(class_metrics, general_metrics)

            print(f"\n✅ Reporte comprensivo completado:")
            print(f"  📄 Reporte detallado: {report_path}")
            print(f"  📊 Gráficos por clase: {plot_path}")
            if df_thresholds is not None:
                print(f"  📈 Análisis de thresholds: {yolo_config.project}/{yolo_config.name}/metrics_vs_threshold.png")

        else:
            print("❌ No se pudieron calcular las métricas")

    except Exception as e:
        print(f"❌ Error creando reporte comprensivo: {e}")

print("✅ Funciones de métricas de clasificación cargadas")

"""## 📊 Análisis Detallado de Métricas de Clasificación"""

# ============================================================
# ANÁLISIS DETALLADO DE MÉTRICAS (EJECUTAR DESPUÉS DEL ENTRENAMIENTO)
# ============================================================

def analyze_trained_model_metrics():
    """Analizar métricas del modelo entrenado"""

    try:
        print("🔄 Analizando métricas del modelo entrenado...")

        # Cargar el mejor modelo entrenado
        best_model_path = f"{yolo_config.project}/{yolo_config.name}/weights/best.pt"
        if not os.path.exists(best_model_path):
            print("❌ No se encontró el modelo entrenado")
            return None, None, None

        model = YOLO(best_model_path)

        # Calcular métricas detalladas
        class_metrics, general_metrics, validation_results = calculate_detailed_metrics(
            model,
            '/content/yolo_data/dataset.yaml',
            conf_threshold=0.5,
            iou_threshold=0.5
        )

        if class_metrics and general_metrics:
            print("✅ Métricas calculadas exitosamente")

            # Crear reporte detallado
            report_path = f"{yolo_config.project}/{yolo_config.name}/final_classification_report.txt"
            create_classification_report(class_metrics, general_metrics, save_path=report_path)

            # Crear tabla resumen
            metrics_df = create_metrics_summary_table(class_metrics, general_metrics)

            # Crear gráficos de métricas
            plot_path = f"{yolo_config.project}/{yolo_config.name}/final_class_metrics_plot.png"
            plot_class_metrics(class_metrics, save_path=plot_path)

            # Guardar métricas en CSV
            csv_path = f"{yolo_config.project}/{yolo_config.name}/final_detailed_metrics.csv"
            save_metrics_to_csv(class_metrics, general_metrics, csv_path)

            # Análisis adicional
            analyze_class_performance(class_metrics, general_metrics)

            return class_metrics, general_metrics, model

        else:
            print("❌ No se pudieron calcular las métricas")
            return None, None, None

    except Exception as e:
        print(f"❌ Error analizando métricas: {e}")
        return None, None, None

def analyze_class_performance(class_metrics, general_metrics):
    """Analizar rendimiento por clase"""

    print("\n" + "="*80)
    print("🔍 ANÁLISIS DE RENDIMIENTO POR CLASE")
    print("="*80)

    # Encontrar la mejor y peor clase
    best_class = max(class_metrics.items(), key=lambda x: x[1]['f1'])
    worst_class = min(class_metrics.items(), key=lambda x: x[1]['f1'])

    print(f"\n🏆 MEJOR CLASE: {best_class[0]}")
    print(f"  F1-Score: {best_class[1]['f1']:.4f}")
    print(f"  Precision: {best_class[1]['precision']:.4f}")
    print(f"  Recall: {best_class[1]['recall']:.4f}")

    print(f"\n⚠️ PEOR CLASE: {worst_class[0]}")
    print(f"  F1-Score: {worst_class[1]['f1']:.4f}")
    print(f"  Precision: {worst_class[1]['precision']:.4f}")
    print(f"  Recall: {worst_class[1]['recall']:.4f}")

    # Análisis de balance
    f1_scores = [metrics['f1'] for metrics in class_metrics.values()]
    f1_std = np.std(f1_scores)
    f1_mean = np.mean(f1_scores)

    print(f"\n📊 ANÁLISIS DE BALANCE:")
    print(f"  F1-Score promedio: {f1_mean:.4f}")
    print(f"  Desviación estándar: {f1_std:.4f}")
    print(f"  Coeficiente de variación: {(f1_std/f1_mean)*100:.2f}%")

    if f1_std < 0.1:
        print("  ✅ Modelo balanceado (baja variación entre clases)")
    elif f1_std < 0.2:
        print("  ⚠️ Modelo moderadamente balanceado")
    else:
        print("  ❌ Modelo desbalanceado (alta variación entre clases)")

    # Recomendaciones
    print(f"\n💡 RECOMENDACIONES:")
    if worst_class[1]['recall'] < 0.5:
        print(f"  - Considerar aumentar datos de entrenamiento para '{worst_class[0]}'")
    if worst_class[1]['precision'] < 0.5:
        print(f"  - Revisar anotaciones de '{worst_class[0]}' para mejorar precisión")
    if f1_std > 0.2:
        print("  - Considerar técnicas de balanceo de clases (focal loss, class weights)")

# Ejecutar análisis si el modelo está entrenado
if train_json and val_json:
    print("🔄 Ejecutando análisis de métricas...")
    class_metrics, general_metrics, trained_model = analyze_trained_model_metrics()
else:
    print("⚠️ Ejecuta el entrenamiento primero para analizar métricas")

"""## 📊 Visualización de Resultados
"""

# Cargar el mejor modelo entrenado (si existe)
best_model_path = f"{yolo_config.project}/{yolo_config.name}/weights/best.pt"
if os.path.exists(best_model_path):
    model = YOLO(best_model_path)
    print("✅ Modelo entrenado cargado para visualización")
else:
    print("⚠️ No hay modelo entrenado disponible para visualización")

# Visualizar curvas de entrenamiento
results_dir = f"{yolo_config.project}/{yolo_config.name}"
if os.path.exists(f"{results_dir}/results.png"):
    display(IPImage(f"{results_dir}/results.png"))

# Mostrar métricas finales
if os.path.exists(f"{results_dir}/results.csv"):
    results_df = pd.read_csv(f"{results_dir}/results.csv")
    print("📊 Métricas de entrenamiento:")
    print(results_df.tail(10))

# Mostrar matriz de confusión
if os.path.exists(f"{results_dir}/confusion_matrix.png"):
    print("\n📊 Matriz de Confusión:")
    display(IPImage(f"{results_dir}/confusion_matrix.png"))

"""## 🔍 Inferencia y Pruebas"""

# Realizar inferencia en imágenes de prueba
if test_json and test_json.exists():
    # Determinar directorio de imágenes de test según el tipo de datos
    if data_type == "standard":
        test_images_dir = TEST_IMG_DIR
    elif data_type == "groundtruth":
        test_images_dir = TEST_IMG_DIR_ALT
    else:
        # Estructura legacy
        test_images_dir = test_json.parent.parent / "test"

    if test_images_dir and test_images_dir.exists():
        test_images = [f for f in os.listdir(test_images_dir) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]

        # Seleccionar algunas imágenes para prueba
        sample_images = test_images[:5]  # Primeras 5 imágenes

        print(f"🔍 Realizando inferencia en {len(sample_images)} imágenes de prueba...")

        for img_name in sample_images:
            img_path = os.path.join(test_images_dir, img_name)

            # Realizar predicción
            results = model(img_path, conf=0.5)

            # Mostrar resultado
            for r in results:
                # Guardar imagen con predicciones
                output_path = f"/content/test_results_{img_name}"
                r.save(output_path)

                # Mostrar imagen
                display(IPImage(output_path))

                # Mostrar estadísticas
                print(f"📊 {img_name}: {len(r.boxes)} objetos detectados")
                if len(r.boxes) > 0:
                    for box in r.boxes:
                        class_id = int(box.cls[0])
                        confidence = float(box.conf[0])
                        class_name = yolo_config.classes[class_id]
                        print(f"  - {class_name}: {confidence:.2f}")
                print()
    else:
        print("⚠️  No se encontró directorio de imágenes de test")
else:
    print("⚠️  No hay datos de test disponibles para inferencia")

"""## 💾 Guardar y Exportar Modelo"""

# Exportar modelo a ONNX para deployment
print("🔄 Exportando modelo a ONNX...")
onnx_path = model.export(format='onnx', imgsz=yolo_config.image_size)
print(f"✅ Modelo exportado a: {onnx_path}")

# Copiar resultados a Google Drive
drive_results_dir = f"/content/drive/MyDrive/aerial-wildlife-count/results/yolov8_{yolo_config.name}"
os.makedirs(drive_results_dir, exist_ok=True)

# Copiar archivos importantes
files_to_copy = [
    f"{results_dir}/weights/best.pt",
    f"{results_dir}/weights/last.pt",
    f"{results_dir}/results.png",
    f"{results_dir}/confusion_matrix.png",
    f"{results_dir}/results.csv",
    onnx_path
]

for file_path in files_to_copy:
    if os.path.exists(file_path):
        filename = os.path.basename(file_path)
        shutil.copy2(file_path, os.path.join(drive_results_dir, filename))
        print(f"📁 Copiado: {filename}")

print(f"✅ Resultados guardados en Google Drive: {drive_results_dir}")

# Mostrar resumen final
print("\n🎉 RESUMEN DEL ENTRENAMIENTO")
print("=" * 50)
print(f"Modelo: {yolo_config.model}")
print(f"Épocas: {yolo_config.epochs}")
print(f"Tamaño de imagen: {yolo_config.image_size}")
print(f"Batch size: {yolo_config.batch_size}")
print(f"Clases: {yolo_config.classes}")
print(f"Mejor modelo: {best_model_path}")
print(f"Modelo ONNX: {onnx_path}")
print(f"Resultados en Drive: {drive_results_dir}")